version: "3.8"

services:
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    volumes:
      - type: bind
        source: ./localhost.crt
        target: /root/localhost.crt
      - type: bind
        source: ./localhost.key
        target: /root/localhost.key
      - type: bind
        source: ./api_gateway/api-gateway.crt
        target: /root/apigateway.crt


    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      GATEWAY_HOST: ${GATEWAY_HOST}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      CONNECTION_SERVICE_HOST: ${CONNECTION_SERVICE_HOST}
      CONNECTION_SERVICE_PORT: ${CONNECTION_SERVICE_PORT}
      AUTHENTICATION_SERVICE_HOST: ${AUTHENTICATION_SERVICE_HOST}
      AUTHENTICATION_SERVICE_PORT: ${AUTHENTICATION_SERVICE_PORT}
      BUSINESS_OFFER_SERVICE_HOST: ${BUSINESS_OFFER_SERVICE_HOST}
      BUSINESS_OFFER_SERVICE_PORT: ${BUSINESS_OFFER_SERVICE_PORT}
    networks:
      - network
  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    volumes:
      - type: bind
        source: ./user_service/logs/info.log
        target: /root/info.log
      - type: bind
        source: ./user_service/logs/error.log
        target: /root/error.log
      - type: bind
        source: ./user_service/user-service.crt
        target: /root/userservice.crt
      - type: bind
        source: ./user_service/user-service.key
        target: /root/userservice.key
      - type: bind
        source: ./user_service/user-service.csr
        target: /root/userservice.csr

    restart: on-failure
    environment:
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      INSERT_USER_COMMAND_SUBJECT: ${INSERT_USER_COMMAND_SUBJECT}
      INSERT_USER_REPLY_SUBJECT: ${INSERT_USER_REPLY_SUBJECT}
    depends_on:
      - user_db
    networks:
      - network

  post_service:
    image: post_service
    container_name: post_service
    build:
      context: .
      dockerfile: ./post_service/Dockerfile
    volumes:
      - type: bind
        source: ./post_service/logs/info.log
        target: /root/info.log
      - type: bind
        source: ./post_service/logs/error.log
        target: /root/error.log
      - type: bind
        source: ./post_service/post-service.crt
        target: /root/postservice.crt
      - type: bind
        source: ./post_service/post-service.key
        target: /root/postservice.key
      - type: bind
        source: ./post_service/post-service.csr
        target: /root/postservice.csr
    restart: on-failure
    environment:
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      POST_DB_HOST: ${POST_DB_HOST}
      POST_DB_PORT: ${POST_DB_PORT}
    depends_on:
      - post_db
    networks:
      - network

  authentication_service:
    image: authentication_service
    container_name: authentication_service
    build:
      context: .
      dockerfile: ./authentication_service/Dockerfile
    restart: on-failure
    volumes:
      - type: bind
        source: ./authentication_service/logs/info.log
        target: /root/info.log
      - type: bind
        source: ./authentication_service/logs/error.log
        target: /root/error.log
      - type: bind
        source: ./authentication_service/authentication-service.crt
        target: /root/authenticationservice.crt
      - type: bind
        source: ./authentication_service/authentication-service.key
        target: /root/authenticationservice.key
      - type: bind
        source: ./authentication_service/authentication-service.csr
        target: /root/authenticationservice.csr
    environment:
      AUTHENTICATION_SERVICE_HOST: ${AUTHENTICATION_SERVICE_HOST}
      AUTHENTICATION_SERVICE_PORT: ${AUTHENTICATION_SERVICE_PORT}
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      INSERT_USER_COMMAND_SUBJECT: ${INSERT_USER_COMMAND_SUBJECT}
      INSERT_USER_REPLY_SUBJECT: ${INSERT_USER_REPLY_SUBJECT}
    depends_on:
      - auth_db
    networks:
      - network

  connection_service:
    image: connection_service
    container_name: connection_service
    build:
      context: .
      dockerfile: ./connection_service/Dockerfile
    volumes:
      - type: bind
        source: ./connection_service/logs/info.log
        target: /root/info.log
      - type: bind
        source: ./connection_service/logs/error.log
        target: /root/error.log
      - type: bind
        source: ./connection_service/connection-service.crt
        target: /root/connectionservice.crt
      - type: bind
        source: ./connection_service/connection-service.key
        target: /root/connectionservice.key
      - type: bind
        source: ./connection_service/connection-service.csr
        target: /root/connectionservice.csr
    restart: on-failure
    environment:
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      INSERT_USER_COMMAND_SUBJECT: ${INSERT_USER_COMMAND_SUBJECT}
      INSERT_USER_REPLY_SUBJECT: ${INSERT_USER_REPLY_SUBJECT}
        - CONNECTION_DB_HOST=${CONNECTION_DB_HOST}
        - CONNECTION_DB_PORT=${CONNECTION_DB_PORT}
        - CONNECTION_SERVICE_PORT=${CONNECTION_SERVICE_PORT}
        - CONNECTION_SERVICE_HOST=${CONNECTION_SERVICE_HOST}
        - CONNECTION_DB_USER=${CONNECTION_DB_USER}
        - CONNECTION_DB_PASS=${CONNECTION_DB_PASS}
    depends_on:
      - neo4j
    networks:
      - network

  business_offer_service:
    image: business_offer_service
    container_name: business_offer_service
    build:
      context: .
      dockerfile: ./business_offer_service/Dockerfile
    restart: on-failure
    volumes:
      - type: bind
        source: ./business_offer_service/logs/info.log
        target: /root/info.log
      - type: bind
        source: ./business_offer_service/logs/error.log
        target: /root/error.log
      - type: bind
        source: ./business_offer_service/business-offer-service.crt
        target: /root/businessofferservice.crt
      - type: bind
        source: ./business_offer_service/business-offer-service.key
        target: /root/businessofferservice.key
      - type: bind
        source: ./business_offer_service/business-offer-service.csr
        target: /root/businessofferservice.csr
    environment:
      - BUSINESS_OFFER_DB_HOST=${BUSINESS_OFFER_DB_HOST}
      - BUSINESS_OFFER_DB_PORT=${BUSINESS_OFFER_DB_PORT}
      - BUSINESS_OFFER_SERVICE_HOST=${BUSINESS_OFFER_SERVICE_HOST}
      - BUSINESS_OFFER_SERVICE_PORT=${BUSINESS_OFFER_SERVICE_PORT}
      - BUSINESS_OFFER_DB_USER=${BUSINESS_OFFER_DB_USER}
      - BUSINESS_OFFER_DB_PASS=${BUSINESS_OFFER_DB_PASS}
    depends_on:
      - neo4jA
    networks:
      - network

  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    networks:
      - network

  post_db:
    image: mongo
    container_name: post_db
    restart: on-failure
    networks:
      - network

  auth_db:
    image: mongo
    container_name: auth_db
    restart: on-failure
    networks:
      - network

  neo4j:
    image: neo4j:4.3.3-community
    container_name: neo4j
    ports:
      - "27474:7474"
      - "27687:7687"
    networks:
      - network
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=512M

  neo4jA:
    image: neo4j:4.3.3-community
    container_name: neo4jA
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - network
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=512M

  nats:
    image: nats
    container_name: nats
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge