// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: common/proto/connection_service/connection_service.proto

package connections

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnectionsServiceClient is the client API for ConnectionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionsServiceClient interface {
	InsertNewUser(ctx context.Context, in *InsertUserRequest, opts ...grpc.CallOption) (*InsertUserResponse, error)
	InsertUserConnection(ctx context.Context, in *InsertUserConnectionRequest, opts ...grpc.CallOption) (*InsertUserConnectionResponse, error)
	GetAll(ctx context.Context, in *GetAllConnectionsRequest, opts ...grpc.CallOption) (*GetAllConnectionsResponse, error)
}

type connectionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionsServiceClient(cc grpc.ClientConnInterface) ConnectionsServiceClient {
	return &connectionsServiceClient{cc}
}

func (c *connectionsServiceClient) InsertNewUser(ctx context.Context, in *InsertUserRequest, opts ...grpc.CallOption) (*InsertUserResponse, error) {
	out := new(InsertUserResponse)
	err := c.cc.Invoke(ctx, "/connections.ConnectionsService/InsertNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionsServiceClient) InsertUserConnection(ctx context.Context, in *InsertUserConnectionRequest, opts ...grpc.CallOption) (*InsertUserConnectionResponse, error) {
	out := new(InsertUserConnectionResponse)
	err := c.cc.Invoke(ctx, "/connections.ConnectionsService/InsertUserConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionsServiceClient) GetAll(ctx context.Context, in *GetAllConnectionsRequest, opts ...grpc.CallOption) (*GetAllConnectionsResponse, error) {
	out := new(GetAllConnectionsResponse)
	err := c.cc.Invoke(ctx, "/connections.ConnectionsService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionsServiceServer is the server API for ConnectionsService service.
// All implementations must embed UnimplementedConnectionsServiceServer
// for forward compatibility
type ConnectionsServiceServer interface {
	InsertNewUser(context.Context, *InsertUserRequest) (*InsertUserResponse, error)
	InsertUserConnection(context.Context, *InsertUserConnectionRequest) (*InsertUserConnectionResponse, error)
	GetAll(context.Context, *GetAllConnectionsRequest) (*GetAllConnectionsResponse, error)
	mustEmbedUnimplementedConnectionsServiceServer()
}

// UnimplementedConnectionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConnectionsServiceServer struct {
}

func (UnimplementedConnectionsServiceServer) InsertNewUser(context.Context, *InsertUserRequest) (*InsertUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertNewUser not implemented")
}
func (UnimplementedConnectionsServiceServer) InsertUserConnection(context.Context, *InsertUserConnectionRequest) (*InsertUserConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertUserConnection not implemented")
}
func (UnimplementedConnectionsServiceServer) GetAll(context.Context, *GetAllConnectionsRequest) (*GetAllConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedConnectionsServiceServer) mustEmbedUnimplementedConnectionsServiceServer() {}

// UnsafeConnectionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionsServiceServer will
// result in compilation errors.
type UnsafeConnectionsServiceServer interface {
	mustEmbedUnimplementedConnectionsServiceServer()
}

func RegisterConnectionsServiceServer(s grpc.ServiceRegistrar, srv ConnectionsServiceServer) {
	s.RegisterService(&ConnectionsService_ServiceDesc, srv)
}

func _ConnectionsService_InsertNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionsServiceServer).InsertNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.ConnectionsService/InsertNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionsServiceServer).InsertNewUser(ctx, req.(*InsertUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionsService_InsertUserConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertUserConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionsServiceServer).InsertUserConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.ConnectionsService/InsertUserConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionsServiceServer).InsertUserConnection(ctx, req.(*InsertUserConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionsService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionsServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.ConnectionsService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionsServiceServer).GetAll(ctx, req.(*GetAllConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionsService_ServiceDesc is the grpc.ServiceDesc for ConnectionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connections.ConnectionsService",
	HandlerType: (*ConnectionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertNewUser",
			Handler:    _ConnectionsService_InsertNewUser_Handler,
		},
		{
			MethodName: "InsertUserConnection",
			Handler:    _ConnectionsService_InsertUserConnection_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ConnectionsService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/connection_service/connection_service.proto",
}
