name: Build
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.18'
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Build
        run: docker-compose build
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}